CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=n
CONFIG_ZMK_HID_INDICATORS=n
# No deep sleep / keep radio+CPU active for max draw.
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_TIMEOUT=86400000
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=10
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_POWER_DRAIN=y
CONFIG_ZMK_POWER_DRAIN_HID_MS=40
CONFIG_ZMK_POWER_DRAIN_STATUS_MS=30000
